
spring:
  datasource:
    url: jdbc:postgresql://localhost:54320/webshop
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: andW8Dw32rE8
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
